---
title: "git_01"
author: "Jean Shepard"
date: "Fall 2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits after each entry
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carroll in this section!-->
He thought he saw an Elephant  
That practised on a fife:  
He looked again, and found it was  
A letter from his wife.  
'At length I realize,' he said,  
'The bitterness of life! '  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I Dwell in a lonely house I know  
That vanished many a summer ago,  
And left no trace but the cellar walls,  
And a cellar in which the daylight falls,  
And the purple-stemmed wild raspberries grow.  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter or any other poem here!-->

Love is like the wild rose-briar,  
Friendship like the holly-tree—  
The holly is dark when the rose-briar blooms  
But which will bloom most constantly?  

The wild rose-briar is sweet in spring,  
Its summer blossoms scent the air;  
Yet wait till winter comes again  
And who will call the wild-briar fair?  

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

I found my strength where shadows used to stay,  
And learned to trust the heart I hid away.  
With every scar, I grew a little more,  
I found myself beyond the fear and doubt,  
And now I stand, stronger than before.  
